# Generated by Django 5.2.2 on 2025-06-09 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(blank=True, default='N/A', max_length=100, null=True),
        ),
    ]
